### ISSUE TITLE
Option to change output format

### ISSUE THREAD

**Issue by contrun** [vzaccaria/pandoc-anki#1]
Hi, thank you for your efforts on this program. I find it really helpful for me to convert some of my notes to anki.

Currently, the output format is LaTeX, which is not quite eye-friendly for documents without many math formula.

Below is what is rendered in HTML
![screenshot-2019-05-17-07-40-15](https://user-images.githubusercontent.com/32609395/57914464-39a77900-787e-11e9-9f74-dd4a9baef7ff.png)

And below is what is rendered in LaTeX
![screenshot-2019-05-17-07-49-34](https://user-images.githubusercontent.com/32609395/57914472-3c09d300-787e-11e9-9b09-dacd2a39e912.png)

I just fiddled around with the code a little bit. I added an option to change render format [here](https://github.com/contrun/pandoc-anki/commit/cd8cc4c2a88163136baa25daf33ae774f6887620). I wonder if you are interested in merging such feature. If so, I will create a pull request.

**Comment by vzaccaria** [comment]
Hi, thanks for checking out pandoc-anki. It started as a personal tool but I am glad you've found it useful. The changes look ok to me. I'll be glad to merge them. Cheers
